- id:         ahoj-svete              # nazev podslozky
  name:       Ahoj světě
  avail:      2020-03-11 16:00:00
  reference:
    name: main.java
    lang: JAVA
    
  tests:
    - id:       case-1.s
      timeout:  1.0
